services:
  # Dịch vụ Web cho ứng dụng Laravel
  - type: web
    name: quan-ly-hoc-vien
    runtime: php  # Render đã hỗ trợ runtime 'php' trực tiếp
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install && npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: quan-ly-hoc-vien # Tên này phải khớp với database bên dưới
          property: connectionString

databases:
  # Dịch vụ Database
  - name: quan-ly-hoc-vien
    plan: free
    # Đã xóa dòng `runtime: postgres` không hợp lệ