services:
  - type: web
    name: quan-ly-hoc-vien
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: quan_ly_hoc_vien # Tên database bạn đã tạo trên Render
          property: internalDatabaseUrl

databases:
  - name: quan_ly_hoc_user
    plan: free
    databaseName: quan_ly_hoc_vien # Tên database cụ thể
    user: quan_ly_hoc_user # Username