services:
  # Dịch vụ Web cho ứng dụng Laravel
  - type: web
    name: quan-ly-hoc-vien
    runtime: php             # SỬA 1: Đổi 'env' thành 'runtime'
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install && npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: quan_ly_hoc_vien # Giữ nguyên tên này, nó khớp với database bên dưới
          property: connectionString # SỬA 2: Đổi 'internalDatabaseUrl' thành 'connectionString'

databases:
  # Dịch vụ Database
  - name: quan_ly_hoc_vien
    runtime: postgres # SỬA 3: Thêm runtime cho database
    plan: free
    # Các thuộc tính databaseName và user không cần thiết khi dùng Blueprint,
    # Render sẽ tự tạo. Nhưng để đó cũng không sao.